test_lca_code_editing__code-editing-metrics-x111db0ba634a45b8__id_36

diff --git a/tests/test_yamls/failed_setup.yaml b/tests/test_yamls/failed_setup.yaml
--- a/tests/test_yamls/failed_setup.yaml
+++ b/tests/test_yamls/failed_setup.yaml
@@ -1,4 +1,12 @@
-setup: |
+s# Failed Setup Section
+echo failed setup
+exit 1
+
+---
+
+# Run Section
+run: |
+  echo run |
   echo failed setup
   exit 1
 
